local config = require("vroom.config")

describe("config", function()
  describe("setup", function()
    it("returns defaults when no opts given", function()
      local cfg = config.setup({})
      assert.equals(true, cfg.map_keys)
      assert.equals(true, cfg.clear_screen)
      assert.equals(false, cfg.write_all)
      assert.equals("rspec", cfg.spec_command)
      assert.equals("rails test", cfg.test_unit_command)
      assert.equals("mix test", cfg.mix_test_command)
      assert.equals("yarn test", cfg.yarn_test_command)
      assert.equals(true, cfg.use_colors)
      assert.equals("./bin", cfg.binstubs_path)
      assert.equals("", cfg.command_prefix)
    end)

    it("overrides specific options", function()
      local cfg = config.setup({ write_all = true, spec_command = "bundle exec rspec" })
      assert.equals(true, cfg.write_all)
      assert.equals("bundle exec rspec", cfg.spec_command)
      -- Other defaults preserved
      assert.equals(true, cfg.map_keys)
    end)

    it("allows custom binstubs_path", function()
      local cfg = config.setup({ binstubs_path = "./vendor/bin" })
      assert.equals("./vendor/bin", cfg.binstubs_path)
    end)
  end)

  describe("get", function()
    it("returns current config after setup", function()
      config.setup({ write_all = true })
      local cfg = config.get()
      assert.equals(true, cfg.write_all)
    end)

    it("returns defaults before setup", function()
      -- Reset by requiring fresh
      package.loaded["vroom.config"] = nil
      local fresh_config = require("vroom.config")
      local cfg = fresh_config.get()
      assert.equals(false, cfg.write_all)
      assert.equals(true, cfg.map_keys)
    end)
  end)
end)
