local runner = require("vroom.runner")
local config = require("vroom.config")

describe("runner", function()
  describe("detect", function()
    it("detects rspec files", function()
      local result = runner.detect("spec/models/user_spec.rb")
      assert.is_not_nil(result)
      assert.equals("spec_command", result.runner)
      assert.equals("ruby", result.type)
    end)

    it("detects minitest _test.rb files", function()
      local result = runner.detect("test/models/user_test.rb")
      assert.is_not_nil(result)
      assert.equals("test_unit_command", result.runner)
      assert.equals("ruby", result.type)
    end)

    it("detects minitest test_*.rb files", function()
      local result = runner.detect("test/test_helper.rb")
      -- test_helper is not a test file pattern — test_*.rb needs a leading /
      -- This should NOT match since it's test_helper, not a real test
    end)

    it("detects minitest /test_*.rb files", function()
      local result = runner.detect("test/unit/test_user.rb")
      assert.is_not_nil(result)
      assert.equals("test_unit_command", result.runner)
      assert.equals("ruby", result.type)
    end)

    it("detects exunit files", function()
      local result = runner.detect("test/my_app/accounts_test.exs")
      assert.is_not_nil(result)
      assert.equals("mix_test_command", result.runner)
      assert.equals("elixir", result.type)
    end)

    it("detects .test.js files", function()
      local result = runner.detect("src/components/Button.test.js")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects .test.ts files", function()
      local result = runner.detect("src/utils/helpers.test.ts")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects .test.tsx files", function()
      local result = runner.detect("src/App.test.tsx")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects .spec.js files", function()
      local result = runner.detect("src/components/Button.spec.js")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects .spec.ts files", function()
      local result = runner.detect("src/utils/helpers.spec.ts")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects __tests__ directory files", function()
      local result = runner.detect("src/__tests__/Button.js")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("detects __tests__ directory ts files", function()
      local result = runner.detect("src/__tests__/helpers.ts")
      assert.is_not_nil(result)
      assert.equals("yarn_test_command", result.runner)
      assert.equals("js", result.type)
    end)

    it("returns nil for non-test files", function()
      assert.is_nil(runner.detect("app/models/user.rb"))
      assert.is_nil(runner.detect("src/components/Button.tsx"))
      assert.is_nil(runner.detect("README.md"))
    end)
  end)

  describe("is_test_file", function()
    it("returns true for test files", function()
      assert.is_true(runner.is_test_file("spec/models/user_spec.rb"))
      assert.is_true(runner.is_test_file("test/models/user_test.rb"))
      assert.is_true(runner.is_test_file("src/Button.test.tsx"))
    end)

    it("returns false for non-test files", function()
      assert.is_false(runner.is_test_file("app/models/user.rb"))
      assert.is_false(runner.is_test_file("src/Button.tsx"))
    end)
  end)

  describe("build_command", function()
    local cfg

    before_each(function()
      cfg = config.setup({})
    end)

    it("builds rspec command with color", function()
      local cmd = runner.build_command("spec/models/user_spec.rb", "", cfg)
      assert.equals("rspec --color spec/models/user_spec.rb", cmd)
    end)

    it("builds rspec command without color", function()
      cfg = config.setup({ use_colors = false })
      local cmd = runner.build_command("spec/models/user_spec.rb", "", cfg)
      assert.equals("rspec spec/models/user_spec.rb", cmd)
    end)

    it("builds rspec command with line number", function()
      local cmd = runner.build_command("spec/models/user_spec.rb", "", cfg, { line = 42 })
      assert.equals("rspec --color spec/models/user_spec.rb:42", cmd)
    end)

    it("builds rails test command", function()
      local cmd = runner.build_command("test/models/user_test.rb", "", cfg)
      assert.equals("rails test --color test/models/user_test.rb", cmd)
    end)

    it("builds rails test command with line number", function()
      local cmd = runner.build_command("test/models/user_test.rb", "", cfg, { line = 10 })
      assert.equals("rails test --color test/models/user_test.rb:10", cmd)
    end)

    it("builds mix test command", function()
      local cmd = runner.build_command("test/accounts_test.exs", "", cfg)
      assert.equals("mix test --color test/accounts_test.exs", cmd)
    end)

    it("builds mix test command with line number", function()
      local cmd = runner.build_command("test/accounts_test.exs", "", cfg, { line = 5 })
      assert.equals("mix test --color test/accounts_test.exs:5", cmd)
    end)

    it("builds yarn test command", function()
      local cmd = runner.build_command("src/Button.test.tsx", "", cfg)
      assert.equals("yarn test src/Button.test.tsx", cmd)
    end)

    it("does not append line number for js tests", function()
      local cmd = runner.build_command("src/Button.test.tsx", "", cfg, { line = 15 })
      assert.equals("yarn test src/Button.test.tsx", cmd)
    end)

    it("prepends prefix to command", function()
      local cmd = runner.build_command("spec/models/user_spec.rb", "bundle exec ", cfg)
      assert.equals("bundle exec rspec --color spec/models/user_spec.rb", cmd)
    end)

    it("prepends binstubs prefix", function()
      local cmd = runner.build_command("spec/models/user_spec.rb", "./bin/", cfg)
      assert.equals("./bin/rspec --color spec/models/user_spec.rb", cmd)
    end)
  end)
end)
